version: '3.8'

services:
  web:
    image: librarywebapp:latest
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"